# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:
  
name: AzureLoginSample2

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALSX }}

    - run: |
        az webapp list --query "[?state=='Running']"
